version: "3.7"

networks:
  default:
    external: true
    name: pshick

services:
  quiz:
    image: "localhost/quiz:${IMAGE_VERSION}"
    ports:
      - 3008:3000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.id == z3er41gllsuylqg839cllksze
